"""Integer (autoincrement) IDs for the remaining surrogate-UUID tables (slice 2).

Converts the surrogate UUID-string primary keys of jobs, ingestion_queue, plans,
ingestion_runs, filter_rules, interaction_log, enrichment_trace,
feedback_corrections, filter_tuning_tasks, enrichers and loopbacks to
``BIGINT GENERATED BY DEFAULT AS IDENTITY``, plus every column that references
one of those ids:

  - ingestion_queue.job_id          -> jobs.id
  - feedback_corrections.item_id    -> items.id
  - feedback_corrections.rule_id    -> filter_rules.id
  - filter_tuning_tasks.rule_id     -> filter_rules.id
  - funnel_stages.item_id           -> items.id
  - filter_rules.created_from_interaction_id -> interaction_log.id

Natural keys are left untouched: source_configs.id (deterministic), processed
(composite), config.key, funnel_order.stage_id. funnel_stages.id is already an
integer autoincrement PK. Assumes EMPTY tables (wipe-and-start-fresh) — see 010.

Revision ID: 011
Revises: 010
Create Date: 2026-06-16
"""

from alembic import op

revision = "011"
down_revision = "010"
branch_labels = None
depends_on = None

_IDENTITY_TABLES = [
    "jobs",
    "ingestion_queue",
    "plans",
    "ingestion_runs",
    "filter_rules",
    "interaction_log",
    "enrichment_trace",
    "feedback_corrections",
    "filter_tuning_tasks",
    "enrichers",
    "loopbacks",
]

# (table, column) references that must move from text to bigint.
_REF_COLS = [
    ("ingestion_queue", "job_id"),
    ("feedback_corrections", "item_id"),
    ("feedback_corrections", "rule_id"),
    ("filter_tuning_tasks", "rule_id"),
    ("funnel_stages", "item_id"),
    ("filter_rules", "created_from_interaction_id"),
]


def _to_identity_pk(table: str) -> None:
    op.execute(f"ALTER TABLE {table} DROP CONSTRAINT {table}_pkey")
    op.execute(f"ALTER TABLE {table} ALTER COLUMN id TYPE bigint USING id::bigint")
    op.execute(
        f"ALTER TABLE {table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
    )
    op.execute(f"ALTER TABLE {table} ADD PRIMARY KEY (id)")


def upgrade() -> None:
    for table in _IDENTITY_TABLES:
        _to_identity_pk(table)
    for table, col in _REF_COLS:
        op.execute(
            f"ALTER TABLE {table} ALTER COLUMN {col} TYPE bigint USING {col}::bigint"
        )


def _to_text_pk(table: str) -> None:
    op.execute(f"ALTER TABLE {table} DROP CONSTRAINT {table}_pkey")
    op.execute(f"ALTER TABLE {table} ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.execute(f"ALTER TABLE {table} ALTER COLUMN id TYPE text USING id::text")
    op.execute(f"ALTER TABLE {table} ADD PRIMARY KEY (id)")


def downgrade() -> None:
    for table, col in _REF_COLS:
        op.execute(
            f"ALTER TABLE {table} ALTER COLUMN {col} TYPE text USING {col}::text"
        )
    for table in _IDENTITY_TABLES:
        _to_text_pk(table)
