import type { FilterTuningTask } from '@/lib/types/feedback'
import { ActionChip } from '@/components/ActionChip'
import { Mono } from '@/components/Mono'
import { Button } from '@/components/ui/button'
import { Sparkles, ArrowRight } from 'lucide-react'

/**
 * FilterTuningCard -- shows an open filter tuning task from the feedback store.
 *
 * Displays the correction context (item, filter, from->to outcome), the
 * proposed prompt, and Apply/Dismiss buttons. Used on the Filters page and
 * the Actions page to surface tuning tasks generated by user corrections.
 */
export function FilterTuningCard({
  task,
  onApply,
  onDismiss,
}: {
  task: FilterTuningTask
  onApply: (taskId: string) => void
  onDismiss: (taskId: string) => void
}) {
  return (
    <div
      data-testid="filter-tuning-card"
      data-task-id={task.id}
      style={{
        padding: 16,
        borderRadius: 'var(--radius-card, 6px)',
        border:
          '1px solid color-mix(in srgb, var(--primary) 35%, var(--border))',
        background: 'color-mix(in srgb, var(--primary) 7%, var(--card))',
      }}
    >
      {/* header */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          marginBottom: 10,
        }}
      >
        <Sparkles size={15} style={{ color: 'var(--brand)' }} />
        <span style={{ fontSize: 13, fontWeight: 600 }}>
          Filter tuning suggestion
        </span>
        <Mono className="text-[11px] text-[var(--muted-foreground)]" style={{ marginLeft: 'auto' }}>
          {task.filterId}
        </Mono>
      </div>

      {/* correction context */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          marginBottom: 10,
          flexWrap: 'wrap',
        }}
      >
        <span
          style={{
            fontSize: 12,
            color: 'var(--muted-foreground)',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            whiteSpace: 'nowrap',
            maxWidth: 200,
          }}
        >
          {task.itemSummary}
        </span>
        <ActionChip action={task.fromOutcome} label={task.fromLabel} small />
        <ArrowRight size={12} style={{ color: 'var(--muted-foreground)' }} />
        <ActionChip action={task.toOutcome} label={task.toLabel} small />
      </div>

      {/* proposed prompt */}
      <div
        data-testid="proposed-prompt"
        style={{
          padding: '10px 12px',
          borderRadius: 'var(--radius-control, 4px)',
          background: 'var(--surface-lowest)',
          border: '1px solid var(--border)',
          marginBottom: 12,
        }}
      >
        <span
          style={{
            fontFamily: 'var(--font-mono)',
            fontSize: 10,
            fontWeight: 600,
            textTransform: 'uppercase',
            letterSpacing: '.06em',
            color: 'var(--muted-foreground)',
            display: 'block',
            marginBottom: 6,
          }}
        >
          Proposed prompt
        </span>
        <p
          style={{
            margin: 0,
            fontSize: 13,
            lineHeight: 1.5,
            fontFamily: 'var(--font-mono)',
          }}
        >
          "{task.proposedPrompt}"
        </p>
      </div>

      {/* actions */}
      <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end' }}>
        <Button
          size="sm"
          variant="ghost"
          onClick={() => onDismiss(task.id)}
          data-testid="dismiss-button"
        >
          Dismiss
        </Button>
        <Button
          size="sm"
          variant="default"
          onClick={() => onApply(task.id)}
          data-testid="apply-button"
        >
          Apply
        </Button>
      </div>
    </div>
  )
}
